apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  #labels related to deployment resources
  labels:
    project: roboshop
    tier: db
    componenet: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      componenet: mongodb
# Pod definitions
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        componenet: mongodb
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:4.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  # servicer labels
  labels:
    project: roboshop
    tier: db
    componenet: mongodb
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: db
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port